#!/bin/sh

#Script to take barcodes in each sample and group them

cd /camp/lab/znamenskiyp/home/shared/projects/turnerb_MAPseq/Sequencing/Processed_data/BRAC5676.1h/trial/unzipped/barcodesplitter


#take only sample barcodes for analysis
awk '{print $3}' barcodes_UMI_final.txt | cut -b 1-30 |sort -nr > barcodes_final_sorted.txt

ml Bowtie

#take each sequence and align to other sequences in the index library (same library, so all to all)
nl barcodes_final_sorted.txt | awk '{print ">" $1 "\n" $2}' > barcodes_final_sorted_fasta.txt; bowtie-build -q barcodes_final_sorted_fasta.txt indexes/final_barcode_fasta; bowtie -v 3 -p 10 -f --best -a indexes/final_barcode_fasta barcodes_final_sorted_fasta.txt bowtiealignment_barcode_1.txt

#take sequence line identifiers and alignments and put in one file
awk '{print $1, $3}' bowtiealignment_barcode_1.txt > bowtiealignment_barcode_2.txt
