from setuptools import setup, find_packages

setup(
    name="MAPseq_preprocess",
    version="v0.1",
    url="https://github.com/znamlab/MAPseq_processing",
    license="MIT",
    author="Znamenskiy lab",
    author_email="benita.turner-bridger@crick.ac.uk",
    description="Tools for processing MAPseq data",
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        "numpy",
        "matplotlib",
        "pandas",
        "scikit-learn",
        "flexiznam @ git+ssh://git@github.com/znamlab/flexiznam.git",
        "opencv-python",
        "seaborn",
        "znamutils @ git+ssh://git@github.com/znamlab/znamutils.git",
        "umi_tools",
        "pyyaml",
        "pynrrd",
        "allensdk",
        "sklearn",
        "bg-atlasapi==1.0.2",
        "statsmodels==0.14.1",
    ],
)
