UMI_collapse_parameters:
  UMI_cutoff: 3
  barcode_range:
  - 1
  - 137
  num_umi: 30000
  pause_before_matching: true
  template_switch_abundance: 8
general_expt_parameters:
  BARCODE_DIR: /nemo/lab/znamenskiyp/home/shared/projects/turnerb_V1_MAPseq/BRAC8198.6c/sample_barcodes.txt
  MOUSE: BRAC8198.6c
  NOTES: 1st V1 HVA MAPseq brain, two sequencing runs of 500M reads
  PROCESSED_DIR: /nemo/lab/znamenskiyp/home/shared/projects
  PROJECT: turnerb_V1_MAPseq
  RAW_DIR: /nemo/lab/znamenskiyp/home/shared/projects/turnerb_V1_MAPseq/BRAC8198.6c/Sequencing
  SCRIPT_PATH: /camp/home/turnerb/home/users/turnerb/code/MAPseq_processing
  SLURM_DIR: /camp/home/turnerb/slurm_logs
sequence_processing_parameters:
  max_reads_per_correction: 10000000
  neuron_bc_length: 32
  neuron_identifier: ^.{30}[CT][CT]
  spike_in_identifier: ^.{24}ATCAGTCA
split_samples_parameters:
  acq_id: [TUR4752A2_S75, TUR4752A2_S171]
  consensus_pos:
  - 37
  - 42
  consensus_seq: GCGGC
  n_mismatch: 2
  overwrite: true
  r1_part:
  - 0
  - 32
  r2_part:
  - 0
  - 30
